package event

const (
	CommandPipelineCancel      = "command.pipeline_cancel"
	HandlerPipelineCancelled   = "handler.pipeline_canceled"
	CommandPipelineFail        = "command.pipeline_fail"
	HandlerPipelineFailed      = "handler.pipeline_failed"
	CommandPipelineFinish      = "command.pipeline_finish"
	HandlerPipelineFinished    = "handler.pipeline_finished"
	CommandPipelineLoad        = "command.pipeline_load"
	HandlerPipelineLoaded      = "handler.pipeline_loaded"
	CommandPipelinePause       = "command.pipeline_pause"
	HandlerPipelinePaused      = "handler.pipeline_paused"
	CommandPipelinePlan        = "command.pipeline_plan"
	HandlerPipelinePlanned     = "handler.pipeline_planned"
	CommandPipelineQueue       = "command.pipeline_queue"
	HandlerPipelineQueued      = "handler.pipeline_queued"
	CommandPipelineResume      = "command.pipeline_resume"
	HandlerPipelineResumed     = "handler.pipeline_resumed"
	CommandPipelineStart       = "command.pipeline_start"
	HandlerPipelineStarted     = "handler.pipeline_started"
	HandlerStepFinished        = "handler.step_finished"
	CommandStepForEachPlan     = "command.step_for_each_plan"
	HandlerStepForEachPlanned  = "handler.step_for_each_planned"
	CommandStepPipelineFinish  = "command.step_pipeline_finish"
	HandlerStepPipelineStarted = "handler.step_pipeline_started"
	CommandStepQueue           = "command.step_queue"
	HandlerStepQueued          = "handler.step_queued"
	CommandStepStart           = "command.step_start"
)
