before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: flowpipe-linux
    binary: golang-cross
    goos:
      - linux
    goarch:
      - amd64
      - arm64

    # Custom ldflags.
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'
    # Templates: allowed
    ldflags:
      # Go Releaser analyzes your Git repository and identifies the most recent Git tag (typically the highest version number) as the version for your release.
      # This is how it determinse the value of {{.Version}}.
      - -s -w -X main.version={{.Version}} -X version.buildTime={{.Date}} -X version.commit={{.Commit}} -X version.builtBy=goreleaser

  - id: flowpipe-darwin
    binary: golang-cross
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w -X main.version={{.Version}} -X version.buildTime={{.Date}} -X version.commit={{.Commit}} -X version.builtBy=goreleaser

release:
  # Always set as pre-release. Publishing release must be done manually.
  prerelease: true

archives:
  - id: homebrew
    format: tar.gz
    name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - ids:
      - homebrew
    name: flowpipe@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    tap:
      owner: turbot
      name: homebrew-tap
      branch: flowpipe-brew
    folder: Formula
    url_template: "https://github.com/turbot/flowpipe/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://flowpipe.io/"
    description: "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
    skip_upload: auto
    install: |-
      bin.install "flowpipe"