name: "20 - DevContainer: Build and Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Flowpipe DevContainer Version (without 'v')"
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: flowpipe

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and push to Container Registry
        id: docker_build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: flowpipe/.devcontainer/build
          push: true
          platforms: linux/arm64,linux/amd64
          build-args: |
            DEVCONTAINER_VERSION=${{ github.event.inputs.version }}
          tags: |
            ghcr.io/turbot/flowpipe-devcontainer:${{ github.event.inputs.version }}
            ghcr.io/turbot/flowpipe-devcontainer:latest
