name: Build and Release Flowpipe DevContainer

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Flowpipe DevContainer"
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@v3
        with:
          path: flowpipe

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and push to Container Registry
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: flowpipe/devcontainer
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ghcr.io/turbot/flowpipe-devcontainer:${{ github.event.inputs.version }}
