name: Build and Release Flowpipe DevContainer

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Flowpipe DevContainer"
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@v3
        with:
          path: flowpipe

      - name: Checkout Flowpipe SDK Go repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.FLOWPIPE_GO_SDK_DEPLOY_PRIVATE_KEY }}
          repository: turbot/flowpipe-sdk-go
          path: flowpipe-sdk-go

      - name: Checkout Terraform Components repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.TERRAFORM_COMPONENTS_DEPLOY_PRIVATE_KEY }}
          repository: turbot/terraform-components
          path: terraform-components
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false # setup-go v4 caches by default, do not change this parameter, check golangci-lint-action doc: https://github.com/golangci/golangci-lint-action/pull/704

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}
      
      - name: Build and push
        run: |
          cd flowpipe/devcontainer
          docker buildx build --push --platform linux/arm64,linux/amd64 --tag ghcr.io/turbot/flowpipe-devcontainer:${{ github.event.inputs.version }} .
