name: "Lint: Flowpipe"
on:
  push:
    branches:
      - "*"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@v3
        with:
          path: flowpipe

      - name: Checkout Flowpipe SDK Go repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.FLOWPIPE_GO_SDK_DEPLOY_PRIVATE_KEY }}
          repository: turbot/flowpipe-sdk-go
          path: flowpipe-sdk-go

      # this is required, check golangci-lint-action docs
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false # setup-go v4 caches by default, do not change this parameter, check golangci-lint-action doc: https://github.com/golangci/golangci-lint-action/pull/704

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

        with:
          version: latest
          args: --timeout=15m
          working-directory: flowpipe
