name: Test - Integration
on:
  push:
    tags:
      - v*
    branches:
      - main
      - "v*"
  workflow_dispatch:
  pull_request:


jobs:
  golangci:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@v3
        with:
          path: flowpipe

      - name: Checkout Pipe Fittings Components repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PIPE_FITTINGS_DEPLOY_PRIVATE_KEY }}
          repository: turbot/pipe-fittings
          path: pipe-fittings
          ref: main

      - name: Checkout Flowpipe SDK Go repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.FLOWPIPE_GO_SDK_DEPLOY_PRIVATE_KEY }}
          repository: turbot/flowpipe-sdk-go
          path: flowpipe-sdk-go
          ref: main

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false # setup-go v4 caches by default, do not change this parameter, check golangci-lint-action doc: https://github.com/golangci/golangci-lint-action/pull/704

      - name: Build UI
        run: make build-ui
        working-directory: flowpipe

      - name: Run tests
        run: make integration-test
        working-directory: flowpipe