name: Flowpipe Unit Tests
# on:
#   push:
#     tags:
#       - v*  
#     branches:
#       - main
#       - "v*"
on:
  pull_request:

jobs:
  unit_test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@v3
        # with:
        #   path: flowpipe
      
      - name: Checkout Flowpipe SDK Go repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.FLOWPIPE_GO_SDK_DEPLOY_PRIVATE_KEY }}
          repository: turbot/flowpipe-sdk-go
          path: flowpipe-sdk-go
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: false

      - name: Run tests
        run: make test
