name: Flowpipe Unit Tests
# on:
#   push:
#     tags:
#       - v*  
#     branches:
#       - main
#       - "v*"
on:
  pull_request:

jobs:
  unit_test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flowpipe repository
        uses: actions/checkout@v3
        # with:
        #   path: flowpipe
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false
  
      - name: Run tests
        run: go test $(go list ./... | grep -v /pipeparser/terraform)
